geodjango/urls.py
from django.conf.urls import url,include
from django.contrib import admin
urlpatterns =[
    url(r'^ipms/',include('ipms.urls','ipms.tms')),
    #url(r'^shape-editor/',include('ipms.tms')),
    url(r'^admin/',admin.site.urls),
    ]

             


            
             
             

ipms/urls.py
from django.conf.urls import url,patterns

from . import views
from . import tms

urlpatterns =[
    url(r'^$',views.listShapefiles,name='listShapefiles'),
    url(r'^import/$',views.importShapefile,name='importShapefile'),
    url(r'^import/import$',views.importShapefile,name='importShapefile'),
    url(r'^export/(?P<shapefile_id>\d+)$',views.exportShapefile,name= 'exportShapefile'),
    url(r'^delete/(?P<shapefile_id>\d+)$',views.deleteShapefile, name='deleteShapefile'),
    url(r'^tms/$',tms.root,name='root'),
    url(r'^tms/(?P<version>[0-9.]+)$',tms.service,name='service'),
    url(r'^tms/(?P<version>[0-9.]+)/' +  r'(?P<shapefile_id>\d+)$',tms.tileMap,name='tileMap'),
    url(r'^tms/(?P<version>[0-9.]+)/' +   r'(?P<shapefile_id>\d+)/(?P<zoom>\d+)/' +  r'(?P<x>\d+)/(?P<y>\d+)\.png$',tms.tile, name='tile'),
    url(r'^edit/(?P<shapefile_id>\d+)$',views.editShapefile,name='editShapefile'), # feature_id = None -> add.
    #url(r'^delete_feature/(?P<shapefile_id>\d+)/' +r'(?P<feature_id>\d+)$',views. delete_feature,          'delete_feature'),
    url(r'^findFeature/$',views.findFeature,name='findFeature'),
    url(r'^editFeature/(?P<shapefile_id>\d+)/' +  r'(?P<feature_id>\d+)$',views.editFeature,name='editFeature'),
    url(r'^geo/$',views.geolocation,name='geolocation'),
    url(r'^st/$',views.ins,name='ins'),
    url(r'^ipmsuna/$',views.ipmsindex,name='ipmsindex'),
    url(r'^ipmsuna/t/$',views.ins,name='ins'),
    url(r'^ipmsuna/u/$',views.studentinstant,name='studentinstant'),
    url(r'^ipmsuna/v/$',views.unastaff,name='unastaff'),
    url(r'^ipmsuna/x/$',views.checkreserve,name='checkreserve'),
    url(r'^ipmsuna/y/$',views.leavespot,name='leavespot'),
    
    
    ]



             


            
             
             

ipms/models.py
from django.contrib.gis.db import models
from django.utils import timezone

# Create your models here.
class BaseMap(models.Model):
    name = models.CharField(max_length=50)
    geometry = models.MultiPolygonField(srid=4326)
    objects = models.GeoManager()
    def __unicode__(self):
        return self.name
    
class Shapefile(models.Model):
    filename = models.CharField(max_length=255)
    srs_wkt = models.TextField(max_length=1000)
    geom_type = models.CharField(max_length=50)
    encoding = models.CharField(max_length=20)
    def __unicode__(self):
        return self.filename

#Shapefile 01(point feature- wgs1984)
class Parkingspot(models.Model):
    filename=models.CharField(max_length=2,blank=True,null=True) 
    pid = models.IntegerField()
    id_sub = models.CharField(max_length=2,blank=True,null=True)
    park_use = models.CharField(max_length=20,blank=True,null=True)
    park_no = models.IntegerField()
    park_name = models.CharField(max_length=50,blank=True,null=True)
    level = models.IntegerField()
    address = models.CharField(max_length=50,blank=True,null=True)
    una = models.FloatField()
    powers_hal = models.FloatField()
    wesleyan_h = models.FloatField()
    mathematic = models.FloatField()
    collier_li = models.FloatField()
    commons = models.FloatField()
    guc = models.FloatField()
    science = models.FloatField()
    art_build = models.FloatField()
    floyd_hall = models.FloatField()
    music_buil = models.FloatField()
    willingham = models.FloatField()
    stevens_ha = models.FloatField(null=True)
    bibb_grave = models.FloatField()
    kellerhall = models.FloatField()
    status=models.IntegerField()
    xcord=models.FloatField()
    ycord=models.FloatField()
    geom = models.MultiPointField(srid=4326)
    
    def __unicode__(self):
        return 'Name: %s' % self.filename  
    
    
    
#Shapefile 02(point feature- wgs1984)      
class Parkinglot(models.Model):
    park_use = models.CharField(max_length=20,blank=True,null=True)
    park_no = models.IntegerField()
    geom = models.MultiPointField(srid=4326)
    xcord=models.FloatField()
    ycord=models.FloatField()
    geom = models.MultiPointField(srid=4326)
    
    def __unicode__(self):
            return self.park_use  
        
#Shapefile 03(Polygon Feature feature- wgs1984)   
class Stopage(models.Model):
    filename=models.CharField(max_length=2,blank=True,null=True)
    sid=models.IntegerField()
    stop = models.CharField(max_length=50,blank=True,null=True)
    geom = models.MultiPolygonField(srid=4326)
        
    def __unicode__(self):
        return 'Name: %s' % self.filename
    
    
    
class Attribute(models.Model):
    shapefile = models.ForeignKey(Shapefile)
    name = models.CharField(max_length=255)
    type = models.IntegerField()
    width = models.IntegerField()
    precision = models.IntegerField()

    
class Feature(models.Model):
    shapefile = models.ForeignKey(Shapefile)
    geom_point = models.PointField(srid=4326,blank=True,null=True)
    geom_multipoint = models.MultiPointField(srid=4326,blank=True,null=True)
    geom_multilinestring = models.MultiLineStringField(srid=4326,blank=True,null=True)
    geom_multipolygon = models.MultiPolygonField(srid=4326,blank=True,null=True)
    geom_geometrycollection = models.GeometryCollectionField(srid=4326,blank=True,null=True)
    objects = models.GeoManager()

    
class AttributeValue(models.Model):
    feature = models.ForeignKey(Feature)
    attribute = models.ForeignKey(Attribute)
    value = models.CharField(max_length=255,blank=True, null=True)
    

class RequestTest(models.Model):
    yourstatus=models.CharField(max_length=30)
    lat=models.FloatField(null=True)
    lon=models.FloatField(null=True)
    destination=models.CharField(max_length=30)
    rdate=models.DateTimeField(verbose_name=None, name=None, auto_now=timezone.now)
    date=models.DateField(auto_now=True)
    parkno=models.IntegerField(default=0)
    pid=models.IntegerField(default=0) 
    pcost=models.FloatField(null=True)
    pprice=models.FloatField(null=True)
    pin=models.CharField(max_length=30)
    
    def __unicode__(self):
            return self.yourstatus         
        


# For form creation. data transfer from html to postgresql= DONE
class Drivers(models.Model):
    yourstatus=models.CharField(max_length=30)
    lat=models.FloatField(null=True)
    lon=models.FloatField(null=True)
    destination=models.CharField(max_length=30)
    rdate=models.DateTimeField(verbose_name=None, name=None, auto_now=timezone.now)
    date=models.DateField(auto_now=True)
    parkno=models.IntegerField(default=0)
    pid=models.IntegerField(default=0) 
    pcost=models.FloatField(null=True)
    pprice=models.FloatField(null=True)
    pin=models.CharField(max_length=30)
    
    def __unicode__(self):
            return self.yourstatus 
        
class DriversStaff(models.Model):
    yourstatus=models.CharField(max_length=30)
    lat=models.FloatField(null=True)
    lon=models.FloatField(null=True)
    destination=models.CharField(max_length=30)
    rdate=models.DateTimeField(verbose_name=None, name=None, auto_now=timezone.now)
    date=models.DateField(auto_now=True)
    parkno=models.IntegerField(default=0)
    pid=models.IntegerField(default=0) 
    pcost=models.FloatField(null=True)
    pprice=models.FloatField(null=True)
    pin=models.CharField(max_length=30)
    
    def __unicode__(self):
            return self.yourstatus 
        
        
class StudentInstant(models.Model):
    yourstatus=models.CharField(max_length=30)
    lat=models.FloatField(null=True)
    lon=models.FloatField(null=True)
    destination=models.CharField(max_length=30)
    rdate=models.DateTimeField(verbose_name=None, name=None, auto_now=timezone.now)
    date=models.DateField(auto_now=True)
    parkno=models.IntegerField(default=0)
    pid=models.IntegerField(default=0) 
    pcost=models.FloatField(null=True)
    pprice=models.FloatField(null=True)
    pin=models.CharField(max_length=30)
    
    def __unicode__(self):
            return self.yourstatus
        
        
        
        
class SpotCheck(models.Model):
    yourid=models.IntegerField(default=0)
    yourstatus=models.CharField(max_length=30)
      
    def __unicode__(self):
            return self.yourstatus 
        
        
class LeaveSpot(models.Model):
    yourid=models.IntegerField(default=0)
    yourstatus=models.CharField(max_length=30)
    yourpin=models.CharField(max_length=30)      
    def __unicode__(self):
            return self.yourstatus
        
        
  
class UNA_STAFF(models.Model):
    ps0021=models.FloatField()
    ps0022=models.FloatField()
    ps0023=models.FloatField()
    ps0024=models.FloatField()
    ps0025=models.FloatField()
    ps0026=models.FloatField()
    ps0027=models.FloatField()
    ps0028=models.FloatField()
    ps0029=models.FloatField()
    ps00210=models.FloatField()
    ps00211=models.FloatField()
    ps00212=models.FloatField()
    ps00213=models.FloatField()
    ps00214=models.FloatField()
    ps00215=models.FloatField()
    ps00216=models.FloatField()
    ps00217=models.FloatField()
    ps00218=models.FloatField()
    ps00219=models.FloatField()
    ps00220=models.FloatField()
    ps00221=models.FloatField()
    ps00222=models.FloatField()
    ps00223=models.FloatField()
    ps00224=models.FloatField()
    ps00225=models.FloatField()
    ps00226=models.FloatField()
    ps00227=models.FloatField()
    ps00228=models.FloatField()
    ps00229=models.FloatField()
    ps00230=models.FloatField()
    ps00231=models.FloatField()
    ps00232=models.FloatField()
    ps00233=models.FloatField()
    ps00234=models.FloatField()
    ps00235=models.FloatField()
    ps00236=models.FloatField()
    ps00237=models.FloatField()
    ps00238=models.FloatField()
    ps00239=models.FloatField()
    ps00240=models.FloatField()
    ps00241=models.FloatField()
    ps00242=models.FloatField()
    ps00243=models.FloatField()
    ps00244=models.FloatField()
    ps00245=models.FloatField()
    ps00246=models.FloatField()
    ps00247=models.FloatField()
    ps00248=models.FloatField()
    ps00249=models.FloatField()
    ps00250=models.FloatField()
    ps00251=models.FloatField()
    ps00252=models.FloatField()
    ps00253=models.FloatField()
    ps00254=models.FloatField()
    ps00255=models.FloatField()
    ps00256=models.FloatField()
    ps00257=models.FloatField()
    ps00258=models.FloatField()
    ps00259=models.FloatField()
    ps00260=models.FloatField()
    ps00261=models.FloatField()
    ps00262=models.FloatField()
    ps00263=models.FloatField()
    ps00264=models.FloatField()
    ps00265=models.FloatField()
    ps00266=models.FloatField()
    ps00267=models.FloatField()
    ps00268=models.FloatField()
    ps00269=models.FloatField()
    ps00270=models.FloatField()
    ps00271=models.FloatField()
    ps00272=models.FloatField()
    ps00273=models.FloatField()
    ps00274=models.FloatField()
    ps00275=models.FloatField()
    ps00276=models.FloatField()
    ps00277=models.FloatField()
    ps00278=models.FloatField()
    ps00279=models.FloatField()
    ps00280=models.FloatField()
    ps00281=models.FloatField()
    ps00282=models.FloatField()
    ps00283=models.FloatField()
    ps00284=models.FloatField()
    ps00285=models.FloatField()
    ps00286=models.FloatField()
    ps00287=models.FloatField()
    ps0041=models.FloatField()
    ps0042=models.FloatField()
    ps0043=models.FloatField()
    ps0044=models.FloatField()
    ps0045=models.FloatField()
    ps0046=models.FloatField()
    ps0047=models.FloatField()
    ps0048=models.FloatField()
    ps0049=models.FloatField()
    ps00410=models.FloatField()
    ps00411=models.FloatField()
    ps0051=models.FloatField()
    ps0052=models.FloatField()
    ps0053=models.FloatField()
    ps0054=models.FloatField()
    ps0055=models.FloatField()
    ps0056=models.FloatField()
    ps0057=models.FloatField()
    ps0058=models.FloatField()

ipms/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from ipms.models import RequestTest
from ipms.models import SpotCheck 
from ipms.models import LeaveSpot 

LABEL_CHOICES = (
    ('django', 'Django'),
    ('python', 'Python'),
)

class EntryForm(forms.ModelForm):
    
    
    
    class Meta:
        model = RequestTest       
        fields = '__all__'#('Yourstatus', 'Lat', 'Lon', 'Destination', 'Date')
        exclude = ['pdate','parkno','pprice','pid','pprice','pcost']
        labels = {'yourstatus': _('Your Status')  }     
         

class EntryFormsStaff(forms.ModelForm):
    
    
    
    class Meta:
        model =SpotCheck      
        fields = '__all__'#('Yourstatus', 'Lat', 'Lon', 'Destination', 'Date')
        exclude = ['id']
        labels = {'yourstatus': _('Your Status')  } 
        
        
CHARACTER_ENCODINGS = [("ascii", "ASCII"),("latin1", "Latin-1"), ("utf8", "UTF-8")]

class ImportShapefileForm(forms.Form):
    import_file = forms.FileField(label="Select a Zipped Shapefile")
    character_encoding = forms.ChoiceField(choices=CHARACTER_ENCODINGS, initial="utf8")
    #name=forms.CharField()

class LeaveSpotForm(forms.ModelForm):
    
    
    
    class Meta:
        model = LeaveSpot       
        fields = '__all__'#('Yourstatus', 'Lat', 'Lon', 'Destination', 'Date')
        exclude = ['pdate','parkno','pprice','pid','pprice','pcost']
        labels = {'yourstatus': _('Your Status')  } 

ipms/templates/deleteFeature.html
<html>
    <head>
        <title>ipms</title>
    </head>
    <body>
        <h1>Delete Feature</h1>
        <form method="POST">
            Are you sure you want to delete this feature?
            </p>
            <button type="submit" name="confirm"
                    value="1">Delete</button>
        </form>
    </body>
</html>

ipms/templates/leavespot.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 5//EN" "http://www.w3.org/TR/html5/strict.dtd">
<html><center> 
  <head>
    
  </head>
  <body> 
   
        <body style="background-color:#9966FF;">
        

       <br/><h1><font color="white">Intelligent Parking Reservation System(IPMS)</font></h1>
       <h2>Leave your parking spot permanently</h2><br/><br/>
       <form action="." method="post" enctype="application/x-www-form-urlencoded" Position: center>

          <tr><th><label for="id_yourid"><font size="6">Your ID:     </label></th><td><input id="id_yourstatus"  name="yourid" type="integer" input style="font-size:30px;" value='' /></td></tr>
          <br/><br/><tr><th><label for="id_yourpin"><font size="6">Your PIN:</label></th><td><input id="id_yourpin"  name="yourpin" type="text" input style="font-size:30px;" value='' /></td></tr>
                      
            <br/><br/><tr><th><label for="id_yourstatus"><font size="6">Your Status:</label></th><td><select id="id_yourstatus"  name="yourstatus" input style="font-size:30px;">
            <option value="ipms_drivers" selected="Student">Student</option>
            <option value="ipms_studentinstant">Student Instant</option>
            <option value="ipms_driversstaff">UNA Staff</option>

            </select></td></tr>
    
            <br/><br/> Click on the button <button type="submit"><font size="6">Leave My Spot</button>
            <br/><h1><font size="7">University of North Alabama(UNA)</h1>
        </form>



  </body></center>
</html>

ipms/templates/reserveparking.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 5//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
  <head>
    <style>

    
      #map {
        width: 500px;
        height: 400px;
        position: absolute; left: 430px; top: 100px;
        border: 2px solid rgba(10, 0, 10, 3);
                
      }
    </style>
  </head>
  <body>
<td xcord='lat'>
<td  ycord='lon'>

    <div id="map"></div>
    <script>
      function initMap() {
        var mapDiv = document.getElementById('map');
        var map = new google.maps.Map(mapDiv, {
          center: {lat: 34.806332542, lng: -87.6777193235339},
          mapTypeId:google.maps.MapTypeId.SATELLITE,
          zoom: 20
        });

        var marker = new google.maps.Marker({
          position: {lat: 34.806332542, lng: -87.6777193235339},
          map: map,
          title: 'Hello World!'
          
        });
       
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?callback=initMap"
        async defer></script>


       <body style="background-color:#9966FF;">

       <form action="." method="post" enctype="application/x-www-form-urlencoded">
          <tr><th><label for="id_yourid">Your ID:</label></th><td><input id="id_yourstatus" name="yourid" type="integer" value='' /></td></tr>
           
            <tr><th><label for="id_yourstatus">Your Status:</label></th><td><select id="id_yourstatus" name="yourstatus">
            <option value="ipms_drivers" selected="Student">Student</option>
            <option value="ipms_studentinstant">Student Instant</option>
            <option value="ipms_driversstaff">UNA Staff</option>

            </select></td></tr>
    
            <button type="submit">Show My Parking Spot</button>
        </form>



  </body>
</html>

ipms/templates/studentinstant.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 5//EN" "http://www.w3.org/TR/html5/strict.dtd">
<html><center>
<head><title>Student Instant Parking</title>
  <h1><font color="white">Input Your Final Destination<b>(Instant Parking) <b/></font></h1>


</head>
<body>
<body style="background-color:#9966FF;">


<form action="." method="post" enctype="application/x-www-form-urlencoded">
    <tr><th><label for="id_yourstatus">Your Status:</label></th><td><input id="id_yourstatus" readonly maxlength="30" name="yourstatus" type="text" value="Student" /></td></tr>
<tr><th><label for="id_lat">Lat:</label></th><td><input id="lat" readonly name="lat" step="any" type="number" /></td></tr>
<tr><th><label for="id_lon">Lon:</label></th><td><input id="lng" readonly name="lon" step="any" type="number" /></td></tr></br></br>
<tr><th><label for="id_pin"><font size="6"> PIN:</label></th><td><input id="id_pin" name="pin" input style="font-size:25px;" type="text"/></td></tr>
<tr><th><label for="id_destination"><font size="6"> Destination:</label></th><td><select id="id_destination" input style="font-size:25px;" name="destination">
<option value="UNA" selected="selected">UNA</option>
<option value="GUC">Gulliot University Center(GUC)</option>
<option value="Commons">Student Commons</option>
<option value="Powers_Hal">Powers Hall</option>
<option value="Wesleyan_H">Wesleyan Hall</option>
<option value="Mathematic">Mathematic/Computer science</option>
<option value="Collier_Li">Collier Library</option>
<option value="Science">Science Building</option>
<option value="Art_Build">Art building</option>
<option value="Floyd_Hall">Floyd Hall</option>
<option value="Music_Buil">Music Building</option>
<option value="Willingham">Willingham Hall</option>
<option value="Stevens_Ha">Stevens Hall</option>
<option value="Bibb_Grave">Bibb Grave Hall</option>
<option value="KellerHall">Keller Hall</option>
</select></td></tr>
    
    <button type="submit"><font size="5">Submit</button>
</form>

<br/><br/>
<div id = "container" style = "width:100%">  


  <div id = "left" style = "float:left; width: 70%;">

<section id="wrapper">
  


<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=False"></script>
    <article>

    </article>
<script>
function success(position) {
  var mapcanvas = document.createElement('div');
  mapcanvas.id = 'mapcontainer';
  mapcanvas.style.height = '400px';
  mapcanvas.style.width = '600px';
  mapcanvas.style.border = '1.5px solid rgba(10, 0, 10, 3)';


  document.querySelector('article').appendChild(mapcanvas);

  var coords = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
  
  var options = {
    zoom: 15,
    center: coords,
    mapTypeControl: false,
    navigationControlOptions: {
      style: google.maps.NavigationControlStyle.SMALL
    },
    mapTypeId: google.maps.MapTypeId.ROADMAP
  };
  var map = new google.maps.Map(document.getElementById("mapcontainer"), options);

  var marker = new google.maps.Marker({
      position: coords,
      map: map,
      title:"You are here!"
  });
}

if (navigator.geolocation) {
  navigator.geolocation.getCurrentPosition(success);
} else {
  error('Geo Location is not supported');
}

</script>
</section>



    <script
src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

<script>

var map;

function initialize() {
var mapOptions = {
zoom: 12
};
map = new google.maps.Map(document.getElementById('map-canvas'),
  mapOptions);

if(navigator.geolocation) {
navigator.geolocation.getCurrentPosition(function(position) {

  var pos = new google.maps.LatLng(position.coords.latitude,
                                   position.coords.longitude);
  document.getElementById('lat').value = position.coords.latitude;
  document.getElementById('lng').value = position.coords.longitude;    
  var marker = new google.maps.Marker({
    map: map,
    position: pos,
    title: 'GPS'
  });

  map.setCenter(pos);
}, function() {
  handleNoGeolocation(true);
});
} else {

handleNoGeolocation(false);
}
}

function handleNoGeolocation(errorFlag) {
if (errorFlag) {
var content = 'Error: The Geolocation service failed.';
} else {
var content = 'Error: Your browser doesn\'t support geolocation.';
}

var options = {
map: map,
position: new google.maps.LatLng(19.043516, -98.198232),
content: content
};

var infowindow = new google.maps.InfoWindow(options);
map.setCenter(options.position);


google.maps.event.addListener(marker, 'GPS', function() {
                var lat = marker.getPosition().lat();
                var lng = marker.getPosition().lng();
                $('#lat').val(lat);
                $('#lng').val(lng);
            });

}

google.maps.event.addDomListener(window, 'load', initialize);

</script></div>
<div id="map-canvas"></div>
<div id ="left" style = "float:left; width: 30%;">

<a href="http://1a9d7f95.ngrok.io/ipms/ipmsuna/"> 
<img src="http://s10.postimg.org/49cugxs8p/instant.png" alt="test.html" style="width:208px;height:330px;margin:40px;"> 
</a>
</div></div> 
<h2><font size="5">Intelligent Parking Reservation System of University of North Alabama</h2> 



</body></center>


</html>

ipms/templates/test.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 5//EN" "http://www.w3.org/TR/html5/strict.dtd">
<html>
<center><head>
  <title>UNA Parking Request</title>
  <h1><font color="white">Input Your Final Destination and Create a PIN <b>(Daily Parking)</font><b/> </h1>


</head>
<body>
<body style="background-color:#9966FF;">



<form action="." method="post" enctype="application/x-www-form-urlencoded">
    <tr><th><label for="id_yourstatus">Your Status:</label></th><td><input id="id_yourstatus" readonly maxlength="30" name="yourstatus" type="text" value="Student" /></td></tr>
<tr><th><label for="id_lat">Lat:</label></th><td><input id="lat" readonly name="lat" step="any" type="number" /></td></tr>
<tr><th><label for="id_lon">Lon:</label></th><td><input id="lng" readonly name="lon" step="any" type="number" /></td></tr></br></br>
<tr><th><label for="id_pin"><font size="6"> PIN:</label></th><td><input id="id_pin" name="pin" input style="font-size:25px;" type="text"/></td></tr>
<tr><th><label for="id_destination"><font size="6"> Destination:</label></th><td><select id="id_destination" input style="font-size:25px;" name="destination">
<option value="UNA" selected="selected">UNA</option>
<option value="GUC">Gulliot University Center(GUC)</option>
<option value="Commons">Student Commons</option>
<option value="Powers_Hal">Powers Hall</option>
<option value="Wesleyan_H">Wesleyan Hall</option>
<option value="Mathematic">Mathematic/Computer science</option>
<option value="Collier_Li">Collier Library</option>
<option value="Science">Science Building</option>
<option value="Art_Build">Art building</option>
<option value="Floyd_Hall">Floyd Hall</option>
<option value="Music_Buil">Music Building</option>
<option value="Willingham">Willingham Hall</option>
<option value="Stevens_Ha">Stevens Hall</option>
<option value="Bibb_Grave">Bibb Grave Hall</option>
<option value="KellerHall">Keller Hall</option>
</select></td></tr>
    
    <button type="submit"><font size="5"> Submit</button>
</form>

<br/><br/>
<div id = "container" style = "width:100%">   


<div id = "left" style = "float:left; width: 70%;">


<section id="wrapper">  


<script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=False"></script>
    <article>

    </article>
<script>
function success(position) {
  var mapcanvas = document.createElement('div');
  mapcanvas.id = 'mapcontainer';
  mapcanvas.style.height = '400px';
  mapcanvas.style.width = '600px';
  mapcanvas.style.border = '1.5px solid rgba(10, 0, 10, 3)';


  document.querySelector('article').appendChild(mapcanvas);

  var coords = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
  
  var options = {
    zoom: 15,
    center: coords,
    mapTypeControl: false,
    navigationControlOptions: {
      style: google.maps.NavigationControlStyle.SMALL
    },
    mapTypeId: google.maps.MapTypeId.ROADMAP
  };
  var map = new google.maps.Map(document.getElementById("mapcontainer"), options);

  var marker = new google.maps.Marker({
      position: coords,
      map: map,
      title:"You are here!"
  });
}

if (navigator.geolocation) {
  navigator.geolocation.getCurrentPosition(success);
} else {
  error('Geo Location is not supported');
}

</script>
</section>



    <script
src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

<script>

var map;

function initialize() {
var mapOptions = {
zoom: 12
};
map = new google.maps.Map(document.getElementById('map-canvas'),
  mapOptions);

if(navigator.geolocation) {
navigator.geolocation.getCurrentPosition(function(position) {

  var pos = new google.maps.LatLng(position.coords.latitude,
                                   position.coords.longitude);
  document.getElementById('lat').value = position.coords.latitude;
  document.getElementById('lng').value = position.coords.longitude;    
  var marker = new google.maps.Marker({
    map: map,
    position: pos,
    title: 'GPS'
  });

  map.setCenter(pos);
}, function() {
  handleNoGeolocation(true);
});
} else {

handleNoGeolocation(false);
}
}

function handleNoGeolocation(errorFlag) {
if (errorFlag) {
var content = 'Error: The Geolocation service failed.';
} else {
var content = 'Error: Your browser doesn\'t support geolocation.';
}

var options = {
map: map,
position: new google.maps.LatLng(19.043516, -98.198232),
content: content
};

var infowindow = new google.maps.InfoWindow(options);
map.setCenter(options.position);


google.maps.event.addListener(marker, 'GPS', function() {
                var lat = marker.getPosition().lat();
                var lng = marker.getPosition().lng();
                $('#lat').val(lat);
                $('#lng').val(lng);
            });

}

google.maps.event.addDomListener(window, 'load', initialize);

</script></div>


<div id="map-canvas"></div>
<div id ="left" style = "float:left; width: 30%;">
  <a href="http://1a9d7f95.ngrok.io/ipms/ipmsuna/"> 
<img src="http://s27.postimg.org/urqxz6bjn/daily.gif" alt="test.html" style="width:208px;height:330px;margin:40px;"></div> </div>
</a>

<h2><font size="6">Intelligent Parking Reservation System of University of North Alabama</h2>


</body></center>


</html>